# Generated by Django 5.0.3 on 2024-05-06 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Username não informado', max_length=100)),
                ('email', models.EmailField(default='default@example.com', max_length=254, unique=True)),
                ('nome_alimento', models.CharField(max_length=200)),
                ('preco', models.FloatField()),
                ('descricao', models.TextField(default='Descrição não informada')),
                ('foto_alimento', models.FileField(upload_to='comida/')),
                ('senha', models.CharField(default='0000', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Username não informado', max_length=100)),
                ('nome_filme', models.CharField(max_length=150)),
                ('email', models.EmailField(default='default@example.com', max_length=254, unique=True)),
                ('duracao', models.PositiveIntegerField()),
                ('descricao', models.TextField(default='Descrição não informada')),
                ('foto_filme', models.FileField(upload_to='poster/')),
                ('senha', models.CharField(default='0000', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.filme')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='minha Review legal!', max_length=10000)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.filme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
