# Generated by Django 5.0.3 on 2024-04-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='cartaz',
            field=models.FileField(upload_to='poster/'),
        ),
    ]
